/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controler.Cauthu;
import MODEL.CauthuMOD;
import SQL.DataValidator;
import SQL.MessagaDialog;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author My PC
 */
public class CauThuPanel extends javax.swing.JPanel {

    private QLiCLB parentForm;
    private DefaultTableModel tblModel;
    private byte[] personalImage;

    public CauThuPanel() {
        initComponents();

        initTable();

        loadDataToTable();

    }

    private void initTable() {
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(new String[]{"Mã CT", "Tên Cầu Thủ", "Ngày Sinh", "Quê Quán", "CMND", "Email", "Vi Trí"});
        jTable1.setModel(tblModel);
    }

    private void loadDataToTable() {
        try {
            Cauthu dao = new Cauthu();
            List<CauthuMOD> list = dao.findAll();
            tblModel.setRowCount(0);
            for (CauthuMOD it : list) {
                tblModel.addRow(new Object[]{
                    it.getMaCT(), it.getTencauthu(), it.getNgaysinh(), it.getQueQuan(), it.getCMND(), it.getEmail(), it.getViTri()
                });
            }
            tblModel.fireTableDataChanged();
        } catch (Exception e) {
            e.printStackTrace();
            MessagaDialog.showErrorDialog(parentForm, e.getMessage(), "Fail");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        add = new javax.swing.JButton();
        ChinhSua = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNgaySinh = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCMND = new javax.swing.JTextField();
        txtQueQuan = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        txtMaCT = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        txtViTri1 = new javax.swing.JTextField();
        btnNew1 = new javax.swing.JButton();
        jComboBox = new javax.swing.JComboBox<>();

        setForeground(new java.awt.Color(102, 255, 102));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setForeground(new java.awt.Color(51, 255, 51));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Cầu Thủ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 930, 10));

        add.setIcon(new javax.swing.ImageIcon("C:\\Users\\My PC\\Documents\\NetBeansProjects\\QUANLIDOIBONG\\src\\image\\plus.png")); // NOI18N
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 290, 100, 50));

        ChinhSua.setIcon(new javax.swing.ImageIcon("C:\\Users\\My PC\\Documents\\NetBeansProjects\\QUANLIDOIBONG\\src\\image\\browser.png")); // NOI18N
        ChinhSua.setText("Update");
        ChinhSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChinhSuaActionPerformed(evt);
            }
        });
        jPanel1.add(ChinhSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 350, 100, 50));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 590, 330));

        jLabel2.setText("Tên Cầu Thủ :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, -1, -1));
        jPanel1.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 160, 110, -1));

        jLabel3.setText("Mã CT :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, -1, -1));
        jPanel1.add(txtNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 220, 110, -1));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 220, 110, -1));

        jLabel4.setText("Email :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, -1, -1));

        jLabel5.setText("CMND :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, -1, -1));

        jLabel6.setText("Quê Quán :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 160, -1, -1));

        txtCMND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCMNDActionPerformed(evt);
            }
        });
        jPanel1.add(txtCMND, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 250, 110, -1));

        txtQueQuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQueQuanActionPerformed(evt);
            }
        });
        jPanel1.add(txtQueQuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 160, 110, -1));

        btnTimKiem.setIcon(new javax.swing.ImageIcon("C:\\Users\\My PC\\Documents\\NetBeansProjects\\QUANLIDOIBONG\\src\\image\\search (1).png")); // NOI18N
        btnTimKiem.setText("Search");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        jPanel1.add(btnTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 100, 100, 30));

        jLabel7.setText("Vị Trí :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 190, -1, -1));

        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });
        jPanel1.add(txtTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 100, 110, 30));

        txtMaCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaCTActionPerformed(evt);
            }
        });
        jPanel1.add(txtMaCT, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 190, 110, -1));

        jLabel8.setText("Ngày Sinh :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 220, -1, -1));

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\My PC\\Documents\\NetBeansProjects\\QUANLIDOIBONG\\src\\image\\delete.png")); // NOI18N
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 350, 100, 50));

        txtViTri1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtViTri1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtViTri1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 190, 110, -1));

        btnNew1.setIcon(new javax.swing.ImageIcon("C:\\Users\\My PC\\Documents\\NetBeansProjects\\QUANLIDOIBONG\\src\\image\\loading.png")); // NOI18N
        btnNew1.setText("Reset");
        btnNew1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNew1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnNew1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 290, 100, 50));

        jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã CT", "Tên Cầu Thủ", "Vị Trí", "Ngày Sinh", "Quê Quán" }));
        jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1074, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtQueQuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQueQuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQueQuanActionPerformed

    private void txtCMNDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCMNDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCMNDActionPerformed

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void txtMaCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaCTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaCTActionPerformed

    private void txtMaCTFocusLost(java.awt.event.FocusEvent evt) {
        try {
            Cauthu dao = new Cauthu();
            CauthuMOD ct = dao.findByID(txtMaCT.getText());
            if (ct != null) {
                txtMaCT.setText(ct.getMaCT());
                txtname.setText(ct.getTencauthu());
                txtNgaySinh.setText(ct.getNgaysinh());
                txtQueQuan.setText(ct.getQueQuan());
                txtCMND.setText(ct.getCMND());
                txtEmail.setText(ct.getEmail());
                txtViTri1.setText(ct.getViTri());

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(txtMaCT, sb, "Mã Cầu Thủ Không Được Để Trống !");
        DataValidator.validateEmpty(txtname, sb, "Tên Cầu Thủ Không Được Để Trống !");

        if (sb.length() > 0) {
            MessagaDialog.showErrorDialog(parentForm, sb.toString(), "Lỗi");
            return;
        }
        try {
            CauthuMOD ct = new CauthuMOD();

            ct.setMaCT(txtMaCT.getText());
            ct.setTencauthu(txtname.getText());
            ct.setNgaysinh(txtNgaySinh.getText());
            ct.setQueQuan(txtQueQuan.getText());
            ct.setCMND(txtCMND.getText());
            ct.setEmail(txtEmail.getText());
            ct.setViTri(txtViTri1.getText());

            Cauthu dao = new Cauthu();
            if (dao.insert(ct)) {
                MessagaDialog.showMessageDialog(parentForm, "Bạn Có Muốn Thêm Thông Tin Cầu Thủ Này Không !", "Thông Báo");
                loadDataToTable();
            } else {
                MessagaDialog.showConfirmDialog(parentForm, "Thêm Thông Tin Không Thành Công", "Lỗi");
            }

        } catch (Exception e) {
            e.printStackTrace();
            MessagaDialog.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }

    }//GEN-LAST:event_addActionPerformed

    private void ChinhSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChinhSuaActionPerformed
        StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(txtMaCT, sb, "Mã Cầu Thủ Không Được Để Trống !");
        DataValidator.validateEmpty(txtname, sb, "Tên Cầu Thủ Không Được Để Trống !");

        if (sb.length() > 0) {
            MessagaDialog.showErrorDialog(parentForm, sb.toString(), "Lỗi");
            return;
        }
        if (MessagaDialog.showConfirmDialog(parentForm, "Bạn có muốn chỉnh sửa thông tin của cầu thủ nảy không ? ", "Thống Bào") == JOptionPane.NO_OPTION) {
            return;
        }

        try {
            CauthuMOD ct = new CauthuMOD();

            ct.setMaCT(txtMaCT.getText());
            ct.setTencauthu(txtname.getText());
            ct.setNgaysinh(txtNgaySinh.getText());
            ct.setQueQuan(txtQueQuan.getText());
            ct.setCMND(txtCMND.getText());
            ct.setEmail(txtEmail.getText());
            ct.setViTri(txtViTri1.getText());

            Cauthu dao = new Cauthu();
            if (dao.update(ct)) {
                MessagaDialog.showMessageDialog(parentForm, "Bạn đã chỉnh sửa thành công !", "Thông bào");
                loadDataToTable();
            } else {
                MessagaDialog.showConfirmDialog(parentForm, "Chỉnh Sửa Thông Tin Không Thành Công", "Lỗi");
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessagaDialog.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_ChinhSuaActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try {
            add.setEnabled(false);
            int row = jTable1.getSelectedRow();

            if (row >= 0) {
                String id = (String) jTable1.getValueAt(row, 0);
                Cauthu dao = new Cauthu();
                CauthuMOD ct = dao.findByID(id);

                if (ct != null) {
                    txtMaCT.setText(ct.getMaCT());
                    txtname.setText(ct.getTencauthu());
                    txtNgaySinh.setText(ct.getNgaysinh());
                    txtQueQuan.setText(ct.getQueQuan());
                    txtCMND.setText(ct.getCMND());
                    txtEmail.setText(ct.getEmail());
                    txtViTri1.setText(ct.getViTri());
                    
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessagaDialog.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
    try {
            Cauthu dao = new Cauthu();
            String a;
            if (jComboBox.getSelectedIndex() == 0) {
                a = "MaCT";
            } else if (jComboBox.getSelectedIndex() == 1) {
                a = "TenCauThu";
            } else if (jComboBox.getSelectedIndex() == 2) {
                a = "ViTri";
            } else if (jComboBox.getSelectedIndex() == 3) {
                a = "Ngaysinh";
            } else {
                a = "QueQuan";
            }
            String b = txtTimKiem.getText();
            List<CauthuMOD> list = new Cauthu().findBy(a, b);
            System.out.println("list size = " + list.size());

            if (list.size() != 0) {
               
                try {

                    tblModel.setRowCount(0);

                    for (CauthuMOD it : list) {
                        tblModel.addRow(new Object[]{
                            it.getMaCT(), it.getTencauthu(), it.getNgaysinh(), it.getQueQuan(), it.getCMND(),
                            it.getEmail(), it.getViTri()
                        });
                    }
                    tblModel.fireTableDataChanged();
                } catch (Exception e) {
                    e.printStackTrace();
                    MessagaDialog.showErrorDialog(parentForm, e.getMessage(), "Lỗi !!!!");
                }

                txtMaCTFocusLost(null);
                
            } else {
                MessagaDialog.showMessageDialog(parentForm, " Không tìm thấy thông tin  !", "Thông báo ");
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessagaDialog.showErrorDialog(parentForm, e.getMessage(), "Lỗii");
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(txtMaCT, sb, "Mã Cầu Thủ Không Được Để Trống !");

        if (sb.length() > 0) {
            MessagaDialog.showErrorDialog(parentForm, sb.toString(), "Lỗi");
            return;
        }
        if (MessagaDialog.showConfirmDialog(parentForm, "Bạn Có Muốn Xóa Cầu Thủ Này Không ? ", "Thông Báo") == JOptionPane.NO_OPTION) {
            return;
        }

        try {

            Cauthu dao = new Cauthu();
            if (dao.delete(txtMaCT.getText())) {
                MessagaDialog.showMessageDialog(parentForm, "Xóa Cầu Thủ Thành Công!", "Thông Báo");
                btnNew1ActionPerformed(evt);
                loadDataToTable();
            } else {
                MessagaDialog.showConfirmDialog(parentForm, "Không Thể Xóa Cầu Thủ Này !", "Lỗi");
            }

        } catch (Exception e) {
            e.printStackTrace();
            MessagaDialog.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtViTri1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtViTri1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtViTri1ActionPerformed

    private void btnNew1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNew1ActionPerformed
        txtname.setText("");
        txtMaCT.setText("");
        txtNgaySinh.setText("");
        txtQueQuan.setText("");
        txtCMND.setText("");
        txtViTri1.setText("");
        txtEmail.setText("");
        txtTimKiem.setText("");
    }//GEN-LAST:event_btnNew1ActionPerformed

    private void jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChinhSua;
    private javax.swing.JButton add;
    private javax.swing.JButton btnNew1;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCMND;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMaCT;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtQueQuan;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtViTri1;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables

    

    
   

}
