/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controler.Cauthu;
import Controler.HLV;
import MODEL.CauthuMOD;
import MODEL.HLVMOD;
import SQL.DataValidator;
import SQL.MessagaDialog;
import static java.awt.AWTEventMulticaster.add;
import static java.awt.AWTEventMulticaster.add;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author My PC
 */
public class HLVPanel extends javax.swing.JPanel {
     private QLiCLB parentForm;
    private DefaultTableModel tblModel;
    private byte[] personalImage;

    /**
     * Creates new form HLVPanel
     */
    public HLVPanel() {
        initComponents();
        
        initTable();

        loadDataToTable();
    }

    private void initTable() {
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(new String[]{"Mã HLV", "Tên HLV", "Ngày Sinh", "Quê Quán", "CMND", "Email", "Chức Vụ", "SDT"});
        jTable2.setModel(tblModel);
    }
    
    private void loadDataToTable() {
        try {
            HLV dao = new HLV();
            List<HLVMOD> list = dao.findAll();
            tblModel.setRowCount(0);
            for (HLVMOD it : list) {
                tblModel.addRow(new Object[]{
                    it.getMaHLV(), it.getTenHVL(), it.getNgaySinh(), it.getQueQuan(), it.getCMND(), it.getEmail(), it.getChucVu(), it.getSDT()
                });
            }
            tblModel.fireTableDataChanged();
        } catch (Exception e) {
            e.printStackTrace();
            MessagaDialog.showErrorDialog(parentForm, e.getMessage(), "Fail");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtTenHLV = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtQueQuan = new javax.swing.JTextField();
        txtCMND = new javax.swing.JTextField();
        txtNgaySinh = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnCapnhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtChucVu = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtMaHLV = new javax.swing.JTextField();
        txtSeach = new javax.swing.JTextField();
        btnXoa1 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("HLV");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 33));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 19, 853, -1));

        jLabel2.setText("Tên HLV :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, -1, -1));

        txtTenHLV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenHLVActionPerformed(evt);
            }
        });
        jPanel1.add(txtTenHLV, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, 110, -1));

        txtSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTActionPerformed(evt);
            }
        });
        jPanel1.add(txtSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 230, 110, -1));

        jLabel4.setText("SĐT :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, -1, -1));

        jLabel6.setText("Email :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 230, 36, -1));

        txtQueQuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQueQuanActionPerformed(evt);
            }
        });
        jPanel1.add(txtQueQuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 170, 110, -1));

        txtCMND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCMNDActionPerformed(evt);
            }
        });
        jPanel1.add(txtCMND, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 200, 110, -1));

        txtNgaySinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgaySinhActionPerformed(evt);
            }
        });
        jPanel1.add(txtNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 260, 110, -1));

        jLabel3.setText("Ngày Sinh :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 59, -1));

        btnThem.setIcon(new javax.swing.ImageIcon("C:\\Users\\My PC\\Documents\\NetBeansProjects\\QUANLIDOIBONG\\src\\image\\plus.png")); // NOI18N
        btnThem.setText("Add");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel1.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 320, 110, 40));

        btnCapnhat.setIcon(new javax.swing.ImageIcon("C:\\Users\\My PC\\Documents\\NetBeansProjects\\QUANLIDOIBONG\\src\\image\\browser.png")); // NOI18N
        btnCapnhat.setText("Update");
        btnCapnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapnhatActionPerformed(evt);
            }
        });
        jPanel1.add(btnCapnhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 320, 110, 40));

        btnXoa.setIcon(new javax.swing.ImageIcon("C:\\Users\\My PC\\Documents\\NetBeansProjects\\QUANLIDOIBONG\\src\\image\\delete.png")); // NOI18N
        btnXoa.setText("Delete");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel1.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, 110, 40));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable2);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 600, 377));

        jLabel5.setText("CMND :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 200, -1, -1));

        jLabel7.setText("Chức Vụ : ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 260, -1, -1));

        txtChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChucVuActionPerformed(evt);
            }
        });
        jPanel1.add(txtChucVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 260, 110, -1));

        jLabel8.setText("Quê Quán :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 170, 62, -1));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 230, 110, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã HVL", "Tên HLV", "Ngày Sinh", "Chức Vụ", "Quê Quán" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 100, -1, 20));

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\My PC\\Documents\\NetBeansProjects\\QUANLIDOIBONG\\src\\image\\search (1).png")); // NOI18N
        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 100, 100, 20));

        jLabel9.setText("Mã HLV :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 200, -1, 20));

        txtMaHLV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaHLVActionPerformed(evt);
            }
        });
        jPanel1.add(txtMaHLV, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 200, 110, -1));

        txtSeach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeachActionPerformed(evt);
            }
        });
        jPanel1.add(txtSeach, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 100, 116, 20));

        btnXoa1.setIcon(new javax.swing.ImageIcon("C:\\Users\\My PC\\Documents\\NetBeansProjects\\QUANLIDOIBONG\\src\\image\\button.png")); // NOI18N
        btnXoa1.setText("Reset");
        btnXoa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnXoa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 370, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDTActionPerformed

    private void txtQueQuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQueQuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQueQuanActionPerformed

    private void txtChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChucVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChucVuActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtNgaySinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgaySinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgaySinhActionPerformed

    private void txtCMNDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCMNDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCMNDActionPerformed

    private void txtTenHLVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenHLVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenHLVActionPerformed

    private void txtMaHLVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaHLVActionPerformed
         try {
            HLV dao = new HLV();
            HLVMOD hlv = dao.findByID(txtMaHLV.getText());
            if (hlv != null) {
                txtMaHLV.setText(hlv.getMaHLV());
                txtTenHLV.setText(hlv.getTenHVL());
                txtNgaySinh.setText(hlv.getNgaySinh());
                txtQueQuan.setText(hlv.getQueQuan());
                txtCMND.setText(hlv.getCMND());
                txtEmail.setText(hlv.getEmail());
                txtChucVu.setText(hlv.getChucVu());
                txtSDT.setText(hlv.getSDT());

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    
    }//GEN-LAST:event_txtMaHLVActionPerformed

    private void txtSeachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeachActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
         StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(txtMaHLV, sb, "Mã Cầu Thủ Không Được Để Trống !");
        DataValidator.validateEmpty(txtTenHLV, sb, "Tên Cầu Thủ Không Được Để Trống !");

        if (sb.length() > 0) {
            MessagaDialog.showErrorDialog(parentForm, sb.toString(), "Lỗi");
            return;
        }
        try {
            HLVMOD hlv = new HLVMOD();

            hlv.setMaHLV(txtMaHLV.getText());
            hlv.setTenHVL(txtTenHLV.getText());
            hlv.setNgaySinh(txtNgaySinh.getText());
            hlv.setQueQuan(txtQueQuan.getText());
            hlv.setCMND(txtCMND.getText());
            hlv.setEmail(txtEmail.getText());
            hlv.setChucVu(txtChucVu.getText());
            hlv.setSDT(txtSDT.getText());

            HLV dao = new HLV();
            if (dao.insert(hlv)) {
                MessagaDialog.showMessageDialog(parentForm, "Bạn Có Muốn Thêm Thông Tin Cầu Thủ Này Không !", "Thông Báo");
                loadDataToTable();
            } else {
                MessagaDialog.showConfirmDialog(parentForm, "Thêm Thông Tin Không Thành Công", "Lỗi");
            }

        } catch (Exception e) {
            e.printStackTrace();
            MessagaDialog.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }

            
        
    }//GEN-LAST:event_btnThemActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        try {
            
            int row = jTable2.getSelectedRow();

            if (row >= 0) {
                String id = (String) jTable2.getValueAt(row, 0);
                HLV dao = new HLV();
                HLVMOD hlv = dao.findByID(id);

                if (hlv != null) {
                    txtMaHLV.setText(hlv.getMaHLV());
                    txtTenHLV.setText(hlv.getTenHVL());
                    txtNgaySinh.setText(hlv.getNgaySinh());
                    txtQueQuan.setText(hlv.getQueQuan());
                    txtCMND.setText(hlv.getCMND());
                    txtEmail.setText(hlv.getEmail());
                    txtChucVu.setText(hlv.getChucVu());
                    txtSDT.setText(hlv.getSDT());
                    
                    
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessagaDialog.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
         StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(txtMaHLV, sb, "Mã HLV Không Được Để Trống !");

        if (sb.length() > 0) {
            MessagaDialog.showErrorDialog(parentForm, sb.toString(), "Lỗi");
            return;
        }
        if (MessagaDialog.showConfirmDialog(parentForm, "Bạn Có Muốn Xóa HLV Này Không ? ", "Thông Báo") == JOptionPane.NO_OPTION) {
            return;
        }

        try {

            HLV dao = new HLV();
            if (dao.delete(txtMaHLV.getText())) {
                MessagaDialog.showMessageDialog(parentForm, "Bạn Đã Xóa Thành Công !", "Thông Báo");
                btnXoa1ActionPerformed(evt);
                loadDataToTable();
            } else {
                MessagaDialog.showConfirmDialog(parentForm, "Không Xóa Được !", "Lỗi");
            }

        } catch (Exception e) {
            e.printStackTrace();
            MessagaDialog.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnXoa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa1ActionPerformed
        txtTenHLV.setText("");
        txtMaHLV.setText("");
        txtNgaySinh.setText("");
        txtQueQuan.setText("");
        txtCMND.setText("");
        txtChucVu.setText("");
        txtEmail.setText("");
        txtSDT.setText("");
    }//GEN-LAST:event_btnXoa1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       try {
            HLV dao = new HLV();
            String a;
            if (jComboBox1.getSelectedIndex() == 0) {
                a = "MaHLV";
            } else if (jComboBox1.getSelectedIndex() == 1) {
                a = "TenHLV";
            } else if (jComboBox1.getSelectedIndex() == 2) {
                a = "NgaySinh";
            } else if (jComboBox1.getSelectedIndex() == 3) {
                a = "ChucVu";
            } else {
                a = "QueQuan";
            }
            String b = txtSeach.getText();
            List<HLVMOD> list = new HLV().findBy(a, b);
            System.out.println("list size = " + list.size());

            if (list.size() != 0) {
               
                try {

                    tblModel.setRowCount(0);

                    for (HLVMOD it : list) {
                        tblModel.addRow(new Object[]{
                            it.getMaHLV(), it.getTenHVL(), it.getNgaySinh(), it.getQueQuan(), it.getCMND(),
                            it.getEmail(), it.getChucVu(), it.getSDT()
                        });
                    }
                    tblModel.fireTableDataChanged();
                } catch (Exception e) {
                    e.printStackTrace();
                    MessagaDialog.showErrorDialog(parentForm, e.getMessage(), "Lỗi !!!!");
                }

                txtMaHLVActionPerformed(null);
                
            } else {
                MessagaDialog.showMessageDialog(parentForm, " Không tìm thấy thông tin  !", "Thông báo ");
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessagaDialog.showErrorDialog(parentForm, e.getMessage(), "Lỗii");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnCapnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapnhatActionPerformed
         StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(txtMaHLV, sb, "Mã Cầu Thủ Không Được Để Trống !");
        DataValidator.validateEmpty(txtTenHLV, sb, "Tên Cầu Thủ Không Được Để Trống !");

        if (sb.length() > 0) {
            MessagaDialog.showErrorDialog(parentForm, sb.toString(), "Lỗi");
            return;
        }
        if (MessagaDialog.showConfirmDialog(parentForm, "Bạn có muốn chỉnh sửa thông tin của cầu thủ nảy không ? ", "Thống Bào") == JOptionPane.NO_OPTION) {
            return;
        }

        try {
            HLVMOD hlv = new HLVMOD();

            hlv.setMaHLV(txtMaHLV.getText());
            hlv.setTenHVL(txtTenHLV.getText());
            hlv.setNgaySinh(txtNgaySinh.getText());
            hlv.setQueQuan(txtQueQuan.getText());
            hlv.setCMND(txtCMND.getText());
            hlv.setEmail(txtEmail.getText());
            hlv.setChucVu(txtChucVu.getText());
            hlv.setSDT(txtSDT.getText());
            
            HLV dao = new HLV();
            if (dao.update(hlv)) {
                MessagaDialog.showMessageDialog(parentForm, "Bạn đã chỉnh sửa thành công !", "Thông bào");
                loadDataToTable();
            } else {
                MessagaDialog.showConfirmDialog(parentForm, "Chỉnh Sửa Thông Tin Không Thành Công", "Lỗi");
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessagaDialog.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btnCapnhatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapnhat;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoa1;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtCMND;
    private javax.swing.JTextField txtChucVu;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMaHLV;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtQueQuan;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtSeach;
    private javax.swing.JTextField txtTenHLV;
    // End of variables declaration//GEN-END:variables

}
