/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controler.Cauthu;
import MODEL.CauthuMOD;
import View.LuongPanel;
import View.CauThuPanel;
import View.HLVPanel;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author My PC
 */
public class QLiCLB extends javax.swing.JFrame {
    
    CauThuPanel mCauThu;
    /**
     * Creates new form QLiCLB
     */
    public QLiCLB() {

        initComponents();
       
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        pnlManage = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jMenu3.setText("jMenu3");

        jMenu5.setText("File");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar2.add(jMenu6);

        jMenu8.setText("File");
        jMenuBar3.add(jMenu8);

        jMenu9.setText("Edit");
        jMenuBar3.add(jMenu9);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 51));

        jPanel1.setBackground(new java.awt.Color(255, 126, 242));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\My PC\\Documents\\NetBeansProjects\\QUANLIDOIBONG\\src\\image\\football-player.png")); // NOI18N
        jButton1.setText("Cầu Thủ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 150, 40));

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\My PC\\Documents\\NetBeansProjects\\QUANLIDOIBONG\\src\\image\\coach.png")); // NOI18N
        jButton2.setText("HLV");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 150, 41));

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\My PC\\Documents\\NetBeansProjects\\QUANLIDOIBONG\\src\\image\\doctor (1).png")); // NOI18N
        jButton3.setText("Y Tế");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 150, 41));

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\My PC\\Documents\\NetBeansProjects\\QUANLIDOIBONG\\src\\image\\budget.png")); // NOI18N
        jButton4.setText("Ngân Sách CLB");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 150, 41));

        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\My PC\\Documents\\NetBeansProjects\\QUANLIDOIBONG\\src\\image\\exit.png")); // NOI18N
        jButton5.setText("Thoát");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 150, 41));

        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\My PC\\Documents\\NetBeansProjects\\QUANLIDOIBONG\\src\\image\\budget.png")); // NOI18N
        jButton6.setText("Lương");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 150, 41));

        pnlManage.setBackground(new java.awt.Color(153, 153, 153));
        pnlManage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 102));
        jLabel1.setText("ỨNG DỤNG QUẢN LÍ ĐỘI BÓNG ");
        pnlManage.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 530, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlManage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
            .addComponent(pnlManage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CauThuPanel x = null;
        try {
            x = new CauThuPanel();

        } catch (Exception ex) {
            Logger.getLogger(QLiCLB.class.getName()).log(Level.SEVERE, null, ex);
        }
//        try {
//            x = new SachJPanel() ;
//        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(GiaoDienChinh.class.getName()).log(Level.SEVERE, null, ex);
//        }
        x.setBounds(0, 0, 1200, 710);
        pnlManage.removeAll();
        pnlManage.add(x);
        pnlManage.validate();
        pnlManage.repaint();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        HLVPanel x = null;
        try {
            x = new HLVPanel();

        } catch (Exception ex) {
            Logger.getLogger(QLiCLB.class.getName()).log(Level.SEVERE, null, ex);
        }
//        try {
//            x = new SachJPanel() ;
//        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(GiaoDienChinh.class.getName()).log(Level.SEVERE, null, ex);
//        }
        x.setBounds(0, 0, 1200, 710);
        pnlManage.removeAll();
        pnlManage.add(x);
        pnlManage.validate();
        pnlManage.repaint();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int click = JOptionPane.showConfirmDialog(null, "Bạn có muốn thoát chương trình ?", "Thông báo", 2);
        if (click == JOptionPane.YES_OPTION) {
            System.exit(0);
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        int click = JOptionPane.showConfirmDialog(null, "Đang Phát Triển Tính Năng !!!!", "Thông báo", 0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         LuongPanel x = null;
        try {
            x = new LuongPanel();

        } catch (Exception ex) {
            Logger.getLogger(QLiCLB.class.getName()).log(Level.SEVERE, null, ex);
        }
//        try {
//            x = new SachJPanel() ;
//        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(GiaoDienChinh.class.getName()).log(Level.SEVERE, null, ex);
//        }
        x.setBounds(0, 0, 1200, 710);
        pnlManage.removeAll();
        pnlManage.add(x);
        pnlManage.validate();
        pnlManage.repaint();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLiCLB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLiCLB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLiCLB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLiCLB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLiCLB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pnlManage;
    // End of variables declaration//GEN-END:variables
}
